carts+brand
SD-1023/Backend-Final-2 pull request #12
Opened 2024-01-21 20:54 UTC by zhala07

2024-01-21 21:55 UTC, MarwanSamamreh commented on src/controllers/cartController.ts
> +      const userId = parseInt(req.params.id);
Follow the same format 
Number(req.params.id);

2024-01-21 21:56 UTC, MarwanSamamreh commented on src/controllers/cartController.ts
> +      const userId = parseInt(req.params.id);
Number

2024-01-21 21:57 UTC, MarwanSamamreh approved these changes

2024-01-22 11:09 UTC, MohammadAhmadKhader requested changes
fit package.json and ts.config to what is on the common structure
npm uninstall the ts-node.
remove the seqeulize from app.ts and stick to the conifg again.
deliveryFee not deliveryFree.
Users must have timestamps.

2024-01-22 15:47 UTC, closed without merging